# your mqtt auth settings here
BROKER_IP="192.168.x.x"
MQTT_USER="your_mqtt_user"
# Use single quotes if your password contains special characters like $ ! etc.
MQTT_PASS='your_mqtt_password'
# typically this needs not to be changed
MQTT_TOPIC_CMD="kiosk/display"
MQTT_TOPIC_STATE="kiosk/display/state"